name: peek_and_pop_dialog
description: A Flutter Widget that shows a dialog on LongPressStart and Hides on LongPressEnd.
version: 0.0.2
homepage: https://github.com/bigblackclock/peek_and_pop_dialog/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
